services:
  db:
    container_name: task_manager_pg
    image: postgres
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    # restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASS}
      - POSTGRES_DB=${DATABASE_NAME}

  codegarden:
    build: .
    container_name: task_manager
    depends_on:
      - db
    ports:
      - ${PORT}:${PORT}
    command: sh -c "npm run dev"
    volumes:
      - .:/usr/app
    env_file:
      - .env
    environment:
      - DATABASE_HOST
      - DATABASE_USER
      - DATABASE_PASS
      - DATABASE_NAME
      - DATABASE_PORT
      - PORT
